// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	todo "github.com/robowealth-mutual-fund/blueprint-service/internals/models/todo"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *Interface) Create(ctx context.Context, request *todo.CreateRequest) (*todo.CreateResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *todo.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *todo.CreateRequest) (*todo.CreateResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *todo.CreateRequest) *todo.CreateResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*todo.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *todo.CreateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, request
func (_m *Interface) Delete(ctx context.Context, request *todo.DeleteRequest) (*todo.DeleteResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *todo.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *todo.DeleteRequest) (*todo.DeleteResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *todo.DeleteRequest) *todo.DeleteResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*todo.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *todo.DeleteRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, request
func (_m *Interface) Get(ctx context.Context, request *todo.GetRequest) (*todo.GetResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *todo.GetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *todo.GetRequest) (*todo.GetResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *todo.GetRequest) *todo.GetResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*todo.GetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *todo.GetRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *Interface) List(ctx context.Context) (*[]todo.ListResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]todo.ListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]todo.ListResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]todo.ListResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]todo.ListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, request
func (_m *Interface) Update(ctx context.Context, request *todo.UpdateRequest) (*todo.UpdateResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *todo.UpdateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *todo.UpdateRequest) (*todo.UpdateResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *todo.UpdateRequest) *todo.UpdateResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*todo.UpdateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *todo.UpdateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
